env = Environment(CCFLAGS='-Wall -Wextra -pedantic -std=c++1y -DNDEBUG -O3')
# env = Environment(CCFLAGS='-Wall -Wextra -pedantic -std=c++1y -g')

common = env.Object(['graph.cpp', 'graph_util.cpp', 'positions.cpp', 'viables.cpp', 'persistence.cpp'])
rendering = env.Object('rendering.cpp')
gllibs = ['GL', 'GLU', 'glfw', 'ftgl']
cmdlibs = ['boost_program_options']
guilibs = gllibs + cmdlibs

env.Program('grapplemap-gui', ['gui.cpp', rendering, common], LIBS=guilibs)
env.Program('grapplemap-playback', ['playback.cpp', rendering, common], LIBS=guilibs)
env.Program('grapplemap-todot', ['todot.cpp', common], LIBS=cmdlibs)
env.Program('grapplemap-browse', ['browse.cpp', 'images.cpp', rendering, common], LIBS=guilibs + ['png', 'boost_filesystem', 'boost_system'])
