env = Environment(CCFLAGS='-Wall -Wextra -pedantic -std=c++11 -DNDEBUG -O3')

common = env.Object(['graph.cpp', 'positions.cpp', 'viables.cpp', 'persistence.cpp'])
rendering = env.Object('rendering.cpp')
guilibs =['glfw', 'GL', 'GLU']

env.Program('jjm-gui', ['gui.cpp', rendering, common], LIBS=guilibs)
env.Program('jjm-playback', ['playback.cpp', rendering, common], LIBS=guilibs)
env.Program('jjm-todot', ['todot.cpp', common])
